Resources:
  NewResource:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.mediaBucketName}
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
  # DataResource:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: ${self:custom.stage}-stream.clarityhub.io


# Outputs:
#   DataResourceArn:
#     Value:
#       Ref: DataResource
        